FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY demo ./demo
COPY app ./app
COPY data ./data

CMD ["uv", "run", "python", "-m", "demo.main"]
