services:
  timescaledb:
    image: ${TIMESCALE_IMAGE:-timescale/timescaledb:latest-pg16}
    container_name: timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-j0lxEv0sljXa}
      TIMESCALEDB_TELEMETRY: "off"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        PYTHON_BASE_IMAGE: ${PYTHON_BASE_IMAGE:-mirror.gcr.io/library/python:3.12}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        NO_PROXY: ${NO_PROXY}
        no_proxy: ${no_proxy}
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:-app_user}:${POSTGRES_PASSWORD:-j0lxEv0sljXa}@timescaledb:5432/${POSTGRES_DB:-app_db}
      API_AUTH_KEY: "pcrt!af3g"
      API_DEV_MODE: "true"
    restart: unless-stopped
    ports:
      - "8000:8000"

  # demo:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.demo
  #     args:
  #       PYTHON_BASE_IMAGE: ${PYTHON_BASE_IMAGE:-public.ecr.aws/docker/library/python:3.12-slim}
  #   environment:
  #     API_URL: http://api:8000
  #     API_AUTH_KEY: ${API_AUTH_KEY:-local-dev-key}
  #     DEMO_BUS: BUS-DEMO
  #     DEMO_CAM_MODE: random
  #     DEMO_CAM: "1,2,3"
  #     DEMO_INTERVAL_SECONDS: "120"
  #     DEMO_BUS_CAMERA_COUNT: "4"
  #     DEMO_TIMEOUT_SECONDS: "10"
  #   depends_on:
  #     - api
