from __future__ import annotations

from alembic import op

revision = "20260701_0003"
down_revision = "20260630_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS bus_trackers (
            device_id BIGINT PRIMARY KEY,
            bus_number VARCHAR(64) NULL
                REFERENCES buses(bus_number)
                ON UPDATE CASCADE
                ON DELETE SET NULL,
            first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            meta_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS bus_trackers_bus_number_idx
        ON bus_trackers(bus_number)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS bus_trackers_last_seen_idx
        ON bus_trackers(last_seen_at DESC)
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS gps_timeline (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            device_id BIGINT NOT NULL
                REFERENCES bus_trackers(device_id)
                ON UPDATE CASCADE
                ON DELETE CASCADE,
            packet_id INTEGER NOT NULL,
            navigation_unix_time BIGINT NOT NULL,
            navigation_time TIMESTAMPTZ NOT NULL,
            received_unix_time BIGINT NOT NULL,
            received_time TIMESTAMPTZ NOT NULL,
            latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
            longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
            geom GEOMETRY(POINT, 4326)
                GENERATED ALWAYS AS (
                    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
                ) STORED,
            speed INTEGER NOT NULL DEFAULT 0,
            pdop INTEGER NOT NULL DEFAULT 0,
            hdop INTEGER NOT NULL DEFAULT 0,
            vdop INTEGER NOT NULL DEFAULT 0,
            nsat INTEGER NOT NULL DEFAULT 0,
            ns INTEGER NOT NULL DEFAULT 0,
            course INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (id, navigation_time)
        )
        """
    )
    op.execute(
        """
        SELECT create_hypertable(
            'gps_timeline',
            'navigation_time',
            if_not_exists => TRUE
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS gps_timeline_device_time_idx
        ON gps_timeline(device_id, navigation_time DESC)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS gps_timeline_packet_idx
        ON gps_timeline(device_id, packet_id, navigation_time DESC)
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS gps_current_position (
            device_id BIGINT PRIMARY KEY
                REFERENCES bus_trackers(device_id)
                ON UPDATE CASCADE
                ON DELETE CASCADE,
            packet_id INTEGER NOT NULL,
            navigation_unix_time BIGINT NOT NULL,
            navigation_time TIMESTAMPTZ NOT NULL,
            received_unix_time BIGINT NOT NULL,
            received_time TIMESTAMPTZ NOT NULL,
            latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
            longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
            geom GEOMETRY(POINT, 4326)
                GENERATED ALWAYS AS (
                    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
                ) STORED,
            speed INTEGER NOT NULL DEFAULT 0,
            pdop INTEGER NOT NULL DEFAULT 0,
            hdop INTEGER NOT NULL DEFAULT 0,
            vdop INTEGER NOT NULL DEFAULT 0,
            nsat INTEGER NOT NULL DEFAULT 0,
            ns INTEGER NOT NULL DEFAULT 0,
            course INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS gps_current_position_geom_gix
        ON gps_current_position USING GIST(geom)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS gps_current_position_time_idx
        ON gps_current_position(navigation_time DESC)
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS gps_current_position_time_idx")
    op.execute("DROP INDEX IF EXISTS gps_current_position_geom_gix")
    op.execute("DROP TABLE IF EXISTS gps_current_position")

    op.execute("DROP INDEX IF EXISTS gps_timeline_packet_idx")
    op.execute("DROP INDEX IF EXISTS gps_timeline_device_time_idx")
    op.execute("DROP TABLE IF EXISTS gps_timeline")

    op.execute("DROP INDEX IF EXISTS bus_trackers_last_seen_idx")
    op.execute("DROP INDEX IF EXISTS bus_trackers_bus_number_idx")
    op.execute("DROP TABLE IF EXISTS bus_trackers")
